/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Вход в систему
         * @description Авторизует пользователя по логину и паролю.
         *     Устанавливает cookies с access и refresh токенами.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Выход из системы
         * @description Удаляет сессию из базы данных и очищает cookies.
         *     Требует авторизации.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить текущего пользователя (me)
         * @description Возвращает информацию об авторизованном пользователе.
         *     Требует авторизации.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Обновление access токена
         * @description Использует refresh token для получения новой пары токенов.
         *     Требует refresh token в cookie или теле запроса.
         */
        post: operations["refresh_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Регистрация нового пользователя
         * @description Создает нового пользователя с указанным логином и паролем.
         *     Автоматически авторизует пользователя и устанавливает cookies.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Проверка здоровья API
         * @description Возвращает текущий статус API, timestamp и версию
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResponseWithTokens: {
            /**
             * @description Access токен (JWT)
             * @example eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
             */
            access_token: string;
            /**
             * Format: int64
             * @description Время жизни токена в секундах
             * @example 86400
             */
            expires_in: number;
            /**
             * @description Refresh токен
             * @example dGhpcyBpcyBhIHJlZnJlc2ggdG9rZW4...
             */
            refresh_token: string;
            /**
             * @description Тип токена
             * @example Bearer
             */
            token_type: string;
            /** @description Данные пользователя */
            user: components["schemas"]["UserResponse"];
        };
        CreateUserRequest: {
            /** @example john_doe */
            login: string;
            /** @example secure_password123 */
            password: string;
        };
        /** @description Расширенный ответ об ошибке */
        ErrorResponse: {
            /** @description Детали ошибки (опционально) */
            details?: components["schemas"]["ValidationError"][] | null;
            /** @description Тип ошибки */
            error: string;
            /** @description Сообщение об ошибке */
            message: string;
        };
        LoginRequest: {
            /**
             * @description Логин пользователя
             * @example john_doe
             */
            login: string;
            /**
             * @description Пароль пользователя
             * @example password123
             */
            password: string;
        };
        /** @description Стандартный ответ с сообщением */
        MessageResponse: {
            /** @description Сообщение от сервера */
            message: string;
        };
        RefreshTokenRequest: {
            /**
             * @description Refresh токен (опционально, если передан в cookie)
             * @example dGhpcyBpcyBhIHJlZnJlc2ggdG9rZW4...
             */
            refresh_token?: string | null;
        };
        UserResponse: {
            /**
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            created_at: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id: string;
            /** @example john_doe */
            login: string;
            role: components["schemas"]["UserRole"];
        };
        /** @enum {string} */
        UserRole: "user" | "admin" | "guest";
        /** @description Детали ошибки валидации */
        ValidationError: {
            /** @description Поле с ошибкой */
            field: string;
            /** @description Описание ошибки */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseWithTokens"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refresh_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Token refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseWithTokens"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseWithTokens"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description User already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API работает нормально */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
